{
    "python.dataScience.sendSelectionToInteractiveWindow": false,
    "python.linting.enabled": true,
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": false,
    "python.pythonPath": "/Users/redpanda/anaconda3",
    "window.zoomLevel": 1,
    "terminal.integrated.inheritEnv": false,
    "workbench.colorTheme": "Dracula",
    "editor.tabCompletion": "on",
    "editor.fontSize": 14,
    "editor.lineHeight": 22,
    "editor.quickSuggestionsDelay": 30,
    "editor.letterSpacing": 0.5,
    "workbench.editor.tabSizing": "shrink",
    "html.format.enable": true,
    "html.format.preserveNewLines": true,
    "files.trimTrailingWhitespace": true,
    "editor.tabSize": 4,
    "editor.cursorWidth": 5,
    // this isn't really underline but we hack it to be a thicker cursor
    "editor.cursorStyle": "line",
    "editor.wordWrap": "on",
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.fontWeight": "400",
    "editor.cursorBlinking": "solid",
    "editor.colorDecorators": false,
    "editor.minimap.enabled": false,
    "editor.renderWhitespace": "none",
    "editor.rulers": [
        80,
        100
    ],
    // show snippets before any other auto completion
    "editor.snippetSuggestions": "top",
    // this lets you quick open multiple items in a row and now have the previous ones closed on you
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "window.title": "${dirty} ${activeEditorMedium}${separator}${rootName}",
    // These are all my auto-save configs
    "editor.formatOnSave": true,
    "editor.autoIndent": "full",
    "window.closeWhenEmpty": true,
    "editor.detectIndentation": false,
    "files.insertFinalNewline": true,
    "editor.showFoldingControls": "always",
    "editor.find.seedSearchStringFromSelection": true,
    "editor.matchBrackets": "always",
    "window.openFilesInNewWindow": "off",
    "workbench.editor.enablePreview": true,
    "editor.scrollBeyondLastLine": true,
    "editor.useTabStops": true,
    "editor.formatOnPaste": true,
    "editor.parameterHints.enabled": false
}
